site_name: Stroke Unit DES
site_url: https://hsma-tools.github.io/jw_hsma_des_stroke_project/
repo_url: https://github.com/hsma-tools/stroke_model_des_hsma

theme:
  name: material
  features:
    - navigation.expand
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.select
    - navigation.top
  palette:
    primary: blue
  icon:
    repo: fontawesome/brands/github

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy

markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: docs
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Home: index.md
  - Running the Model:
    - Try the Model Online: app.md
    - Run the Model Locally: running_locally.md
  - Model Classes:
    - g: g.md
    - Patient: patient.md
    - Model: model.md
    - Trial: trial.md
    - Metrics: metrics.md
    - Metrics Snapshot: metricsSnapshot.md
  - Model Details:
    - Pathway Diagram: pathway_diagram.md
    - STRESS DES Checklist: stress_des.md
    - Code Tests: tests.md
  - Changelog: CHANGELOG.md
